### ISSUE TITLE
Rails Admin doesn't load default theme

### ISSUE THREAD

**Issue by vorant94** [sferik/rails_admin#2325] opened 2015-06-10 19:25 UTC
I can't understand it at all. If I'm right there is a default theme of rails admin:
![screenshot of right style](http://s15.postimg.org/azddcna3v/Screenshot_from_2015_06_10_21_56_54.png)

And as you see I've managed somehow make it work in my rails app, but after several commits it returned back to this
![screenshot of wrong style]
(http://s12.postimg.org/64uvxji9p/Screenshot_from_2015_06_10_21_56_31.png)

Please help me to make it right

**Comment by mshibuya** [comment] 2015-06-11 03:21
Can you create minimal app to reproduce this problem?

**Comment by vorant94** [comment] 2015-06-11 07:36
here it is on [github](https://github.com/vorant94/hello_world) and on [heroku](https://shrouded-tundra-2649.herokuapp.com/admin)

**Comment by mshibuya** [comment] 2015-06-11 07:44
> but after several commits

What did you do in those commits?
How can I reproduce this unintentional change of appearance?

**Comment by vorant94** [comment] 2015-06-11 07:59
> What did you do in those commits?

look for example [here](https://shrouded-tundra-2649.herokuapp.com/admin) and [github of this](https://github.com/vorant94/hello_world)
as you asked I've created minimal app: 
* create app
* add rails_admin
* generate rails_admin:install 

that's all. and you see, styles are the same as on second screenshot

**Comment by mshibuya** [comment] 2015-06-11 08:25
> styles are the same as on second screenshot

There's nothing wrong with it. This is exactly what the latest RailsAdmin looks like.
 
I'm pretty confused, what is wrong with RailsAdmin?

**Comment by rikkipitt** [comment] 2015-06-11 09:14
It just looks like the rails_gem has been updated and the assets have been cleared... the second screenshot is of the latest rails_admin. The first is an earlier version.

If you want the former, I suggest using an older release. E.g.

```gem "rails_admin", "0.6.5"```

I'm not sure how many releases back you need to go to get that old layout... Probably best to just keep updated though!

**Comment by vorant94** [comment] 2015-06-11 09:51
> This is exactly what the latest RailsAdmin looks like.

Ok, but I don't know is it normal that check-box has strange highlight and there is unnecessary scroll-bar at the bottom of the page
![](http://i.imgur.com/aGvuBfu.png)

I considered because of it, that something wrong with styles. 
But check-box and scroll-bar are ok with this "old" theme
![](http://i.imgur.com/Z7UeUr6.png)

**Comment by rikkipitt** [comment] 2015-06-11 09:55
Hi @vorant94 I think these small issues have been fixed but probably not released as a version... to get around this and get the latest edge version of rails_admin, try this:

```gem "rails_admin", github: "sferik/rails_admin"```

Bundle then restart your local server and see if that helps!

Rikki

**Closed** 2015-06-11 10:06 UTC
Labels: needs info

**Comment by mshibuya** [comment] 2015-06-11 10:09
Ah, it was as simple as that...
@rikkipitt Thanks for the help!
