### ISSUE TITLE
Sass::SyntaxError in RailsAdmin::Main#dashboard with 0.8

### ISSUE THREAD

**Issue by mtparet** [sferik/rails_admin#2481] opened 2015-11-23 12:22 UTC
I just upgraded an existing version from 0.7 to 0.8 and I got an error:
![selection_100](https://cloud.githubusercontent.com/assets/754770/11336383/2697eb66-91e5-11e5-9b1b-f556a9454cb7.jpg)

**Comment by tnlin** [comment] 2015-11-23 13:12
I have exactly the same problem!!!!!!!
debugging all night but got nothing
(This is my first time using RA, so depressive)

**Comment by bensheldon** [comment] 2015-11-23 15:14
It seems like #2391 (Replace jQueryUI datetimepicker with jQuery Bootstrap datetimepicker) added assets to `/vendor`, but they aren't being picked up in the SASS loadpaths. Also, it seems like the `/vendor` directory [was not added to the gemspec](https://github.com/sferik/rails_admin/blob/master/rails_admin.gemspec#L25) which may be why they aren't in the SASS loadpaths.

**Comment by bensheldon** [comment] 2015-11-23 15:23
FYI, the problem is the gemspec is not packaging the `vendor` directory. For a quick fix until this is fixed in the packaged version, you can change your gemfile declaration to:

`gem 'rails_admin', github: 'sferik/rails_admin'`

**Comment by monkbroc** [comment] 2015-11-23 15:55
I came to report this too. `vendor` is missing from the gemspec.

**Comment by natebeaty** [comment] 2015-11-23 20:38
+1. @bensheldon fix worked for me for now.

**Comment by mshibuya** [comment] 2015-11-24 02:09
Sorry about that :bow:
Just released the fix as 0.8.1.

**Closed by mshibuya** 2015-11-24 02:09 UTC

**Comment by monkbroc** [comment] 2015-11-24 02:22
Arigatou Shibuya-san!

Thanks for your efforts in maintaining rails admin!

**Comment by Hainminsoe** [comment] 2017-02-02 16:50
i'm newbie in ror, please tell me . how can i fix it.
