### ISSUE TITLE
Add after_ and before_ action hooks

### ISSUE THREAD

**Issue by twist900** [sferik/rails_admin#2996] opened 2018-03-05 14:25 UTC
When creating/updating specific models, I sometimes need to perform some custom extra steps, for instance send out emails or send out API requests. For these extra action I need controller specific data like the current user and action parameters. Usually I would do this in action before_ and after_ hooks, like seen in ActiveAdmin gem. How would one go about doing it in rails admin?

I have seen a few similar issues opened, but they are now closed or left unanswered. Please enlighten me on how to add this essential functionality?

**Comment by mshibuya** [comment] 2019-05-25 07:04
Duplicate of #1293.

**Closed by mshibuya** 2019-05-25 07:04 UTC
