### ISSUE TITLE
No multi-select box for enum fields

### ISSUE THREAD

**Issue by dblarons** [sferik/rails_admin#3362] opened 2021-06-06 04:29 UTC
Rails Admin Version: 2.1.1
Ruby Version: 2.7.3
Rails Version: 6.1.3

----

About a month ago we upgraded our dependencies from Rails 6.0.3 to 6.1.3 and Rails Admin from 2.0.2 to 2.1.1. On the old version, we could multi-select enum field filters. What would happen is when we filtered for an enum, a box would show up next to the select box and if we held the command button on mac and clicked on multiple of the fields, it would filter multiple. It was one of our favorite features.

After the upgrade the box is gone. I've attached a picture below. There are no Javascript errors in the console and otherwise everything seems fine.

I've looked through the [diff](https://github.com/sferik/rails_admin/compare/v2.0.2...v2.1.1) for 2.0.2 -> 2.1.1 and nothing stuck out to me as problematic in either the commit comments or the code. Same with the changelog. The only thing in the 2.1.1->Head diff that stuck out was [this](https://github.com/sferik/rails_admin/compare/v2.1.1...HEAD#diff-582cb58540b4ca69d56e738b647db71c6f7bee1d5e8f5f664af5f90d62d2117dR175).

Is this a known change? I haven't seen it in any issues. Hope there's a fix or way to enable it because that multi select feature was awesome.

<img width="541" alt="Screen Shot 2021-06-06 at 12 17 15 AM" src="https://user-images.githubusercontent.com/1482167/120912533-07803400-c65e-11eb-8419-2e37287531aa.png">

**Comment by mshibuya** [comment] 2021-06-15 09:14
Caused by #3340, now fixed in the master.

**Closed** 2021-06-15 09:13 UTC

**Comment by dblarons** [comment] 2021-06-15 13:37
Awesome—thanks!
