### ISSUE TITLE
Ruby 3.0.0, Rails 6.1.3 - wrong number of arguments (given 1, expected 0)

### ISSUE THREAD

**Issue by lfuszara1** [sferik/rails_admin#3342] opened 2021-02-20 10:06 UTC
**ArgumentError in RailsAdmin::MainController#new**
wrong number of arguments (given 1, expected 0)

```
    def save(**) # :nodoc:
      SuppressorRegistry.suppressed[self.class.name] ? true : super
    end
```

[https://rubyreferences.github.io/rubychanges/3.0.html#keyword-arguments-are-now-fully-separated-from-positional-arguments](https://rubyreferences.github.io/rubychanges/3.0.html#keyword-arguments-are-now-fully-separated-from-positional-arguments)

---

Problem is probably connected with new way of declaring keyword arguments. 

```
def old_style(name, options = {})
end

def new_style(name, **options)
end
```

**Comment by toddsiegel** [comment] 2021-02-22 15:35
As far as I can tell this is fixed on [master](https://github.com/sferik/rails_admin/blob/f0c46f1e128b5d31d812ff3a80d15db8692c848b/lib/rails_admin/adapters/active_record/abstract_object.rb#L23), but not released yet.

In the meantime, I have my `Gemfile` pointing there: `gem 'rails_admin', github: 'sferik/rails_admin'`. So far it's resolved the issue (without introducing new ones).

**Comment by RocKhalil** [comment] 2021-02-25 09:20
@toddsiegel yes and no.
It actually fails when you have a custom action and its related views.

**Comment by mshibuya** [comment] 2021-02-28 08:26
@RocKhalil I could not reproduce that, how does the custom action look like?
Can you provide reproducible code?

**Comment by RocKhalil** [comment] 2021-03-03 08:09
@mshibuya sorry for the late reply, here's an example:

action:
```
RailsAdmin.config do |config|
  config.actions do

    member :my_custom_action do
      pjax false # very important when using a React component
      i18n_key :my_custom_action
      link_icon 'fa fa-music'
      only [Song]
      http_methods { [:post, :get] }

      controller do
        proc do
          if request.get?
            if request.format.json?
              render json: { data: @object.my_custom_action }, status: :ok
            end
          elsif request.post?
            render json: {
              success: @object.my_custom_action_with_params!(random_param: params[:random_param])
            },
            status: :ok
          end
        end
      end
    end

  end
end
```

And here's my view:
```
<%= javascript_pack_tag 'react-bundle' %>

<%= react_component("MyReactComponent", props: {
  customProps: @object.cutom_method(mode: :custom_mode)
}, prerender: false) %>
```


Of course, I've changed the method names, etc..
But, both:
```
@object.my_custom_action_with_params!(random_param: params[:random_param])
AND
@object.cutom_method(mode: :custom_mode)
```
are breaking. If you remove the named param and use `@object.cutom_method(:custom_mode)` instead, it will work.

**Comment by mshibuya** [comment] 2021-03-03 08:46
I see, so the problem is in your code. You need to fix it yourself.

**Comment by RocKhalil** [comment] 2021-03-03 08:51
@mshibuya how is the issue in my code ? :-p
If I move my code to another view, it runs perfectly. However, when it runs using Rails Admin's binding it throws an error.

**Comment by mshibuya** [comment] 2021-03-03 08:52
Please forget about it, I found something suspicious.
https://github.com/sferik/rails_admin/blob/master/lib/rails_admin/adapters/active_record/abstract_object.rb#L26-L28

**Closed** 2021-03-03 10:40 UTC

**Comment by mshibuya** [comment] 2021-03-03 10:42
I've just pushed the fix to the master, please try and see if it works.

**Comment by RocKhalil** [comment] 2021-03-03 10:52
Yup, works like a charm !
Thanks for the quick update.
